global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity', 'instance']
  group_wait: 45s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'dummy-webhook'
  routes:
  - match:
      severity: warning
    receiver: dummy-webhook-warn
    routes:
    - match_re:
        team: .*(devops).*
      receiver: dummy-webhook-devops

receivers:
- name: 'dummy-webhook'
  webhook_configs:
    - url: http://webhook:8686/default
- name: 'dummy-webhook-warn'
  webhook_configs:
    - url: http://webhook:8686/warning
- name: 'dummy-webhook-devops'
  webhook_configs:
    - url: http://webhook:8686/devops
